"""add_llm_configs_table

Revision ID: f9d8f6e0b502
Revises: 32dc8f1a0417
Create Date: 2026-02-10 10:16:19.036459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d8f6e0b502'
down_revision: Union[str, None] = '32dc8f1a0417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_configs_user_id'), 'llm_configs', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_configs_user_id'), table_name='llm_configs')
    op.drop_table('llm_configs')
    # ### end Alembic commands ###
